# Todo: check this config
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - prettier
overrides: []
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
root: true
rules:
  arrow-body-style: off
  camelcase: off
  class-methods-use-this: off
  comma-dangle: off
  eol-last: off
  func-names: off
  global-require: off
  linebreak-style: off
  no-console: off
  no-multiple-empty-lines: warn
  no-trailing-spaces: warn
  no-underscore-dangle: off
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': 0
  object-curly-newline: off
  operator-linebreak: off
  prefer-promise-reject-errors: off
  no-unused-expressions: off
  no-plusplus: off
  no-restricted-syntax: off
  import/prefer-default-export: off
  no-useless-constructor: off
  no-param-reassign: off
  no-undef: off
  import/extensions: off
  '@typescript-eslint/ban-ts-comment': off
  import/no-extraneous-dependencies: off
