# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
exclude: >
  (?x)^(
      apps/.*/migrations/.* |
      manage.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)^(
              static/.*\.min\.(js|css)$|
              static/.*/bootstrap/.*|
              static/.*/htmx/.*
          )$
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
              static/.*\.min\.(js|css)$|
              static/.*/bootstrap/.*|
              static/.*/htmx/.*
          )$
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        exclude: >
          (?x)^(
            static/.*\.map$|
            static/.*\.min\.(js|css)$|
            static/.*/bootstrap/.*|
            static/.*/htmx/.*|
            static/fonts/.*\.ttf$
          )$
      - id: check-merge-conflict
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff # Run the linter.
      - id: ruff-format # Run the formatter.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.25.0
    hooks:
      - id: django-upgrade
        args:
          - --target-version=5.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        args:
          - --no-strict-optional
          - --ignore-missing-imports
          - --enable-incomplete-feature=Unpack
        additional_dependencies:
          - celery
          - django-celery-beat
          - django-celery-results
          - django-debug-toolbar
          - django-import-export
          - django-linear-migrations
          - django-phonenumber-field
          - django-stubs
          - django-widget-tweaks
          - django_htmx
          - djangorestframework
          - djangorestframework-stubs
          - drf-spectacular
          - drf-spectacular-sidecar
          - pandas
          - phonenumberslite
          - psycopg
          - environs
          - python-decouple
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.8
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.28.0
    hooks:
      - id: eslint
        files: ^static/
        types: [ javascript, ts ]
        exclude: >
          (?x)^(
              static/.*\.min\.(js|css)$|
              static/.*/bootstrap/.*|
              static/.*/htmx/.*
              static/src/.*
          )$
        args:
          - --fix
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: check-novalidate
        name: Check for <form novalidate>
        description: Check for the HTML form attribute `novalidate`.
        language: pygrep
        entry: novalidate
        types: [ html ]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
