# Generated by Django 5.2 on 2025-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="url",
            field=models.CharField(max_length=200),
        ),
    ]
