# Generated by Django 5.2 on 2025-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_social_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="social",
            name="show_in_navbar",
            field=models.BooleanField(default=False),
        ),
    ]
