# Generated by Django 5.2 on 2025-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_social_show_in_navbar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biography",
            old_name="text",
            new_name="text_en",
        ),
        migrations.AddField(
            model_name="biography",
            name="text_es",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
