# Generated by Django 5.2 on 2025-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_text_biography_text_en_biography_text_es"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biography",
            name="text_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
