# Generated by Django 5.2 on 2025-06-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_biography_text_en"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="greeting",
            new_name="greeting_es",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="role",
            new_name="role_es",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="welcome_text",
            new_name="welcome_text_es",
        ),
        migrations.AddField(
            model_name="profile",
            name="greeting_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="role_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="welcome_text_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
