# Generated by Django 5.2 on 2025-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_greeting_profile_greeting_es_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="position",
            new_name="position_es",
        ),
        migrations.AddField(
            model_name="work",
            name="position_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
