# Generated by Django 5.2 on 2025-06-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_position_work_position_es_work_position_en"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="end",
            new_name="end_es",
        ),
        migrations.RenameField(
            model_name="work",
            old_name="start",
            new_name="start_es",
        ),
        migrations.AddField(
            model_name="work",
            name="end_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="start_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
