# Generated by Django 5.2 on 2025-06-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='blogspost',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='unique_slug_per_language'),
        ),
    ]
